### ISSUE TITLE
Struct serialization? External serialization?

### ISSUE THREAD

**Issue by helikopterodaktyl** [huntlabs/hunt-xml#2]
1. Is it possible to serialize structs too? e.g. 

```
struct Vector3 {
 float x, y, z; 
} 
```
` 

2. Is it possible to define custom serialization routines outside of the struct/class? e.g.

```
class Foo {
   ...
}

void serializeToXml(XmlSerializer xs, Foo foo)
{
  ...
}

Foo deserializeFromXml(XmlDeserializer xs)
{
  ...
}
```

**Comment by Heromyth** [comment]
> Is it possible to serialize structs too? e.g.

It's fixed in commit https://github.com/huntlabs/hunt-xml/commit/d3c5d55c4178db59abba3682c54798f12c2a4490


> Is it possible to define custom serialization routines outside of the struct/class? e.g.

We defined a interface XmlSerializable which can be used for a class. See [here](https://github.com/huntlabs/hunt-xml/blob/master/examples/UnitTest/source/test/SerializerTest.d#L81).

Maybe, it would be improved to support a struct.
